server:
  port: 8888
  
spring:  cloud:    config:      server:        git:          uri: https://github.com/renatooa/spring-boot-microservice-config
          search-paths: fornecedor, loja, transportador